name: test
on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'py39-cover (ubuntu)'
            python: '3.9'
            python_arch: 'x64'
            os: 'ubuntu-latest'
          - name: 'py39-cover (windows)'
            python: '3.10'
            python_arch: 'x64'
            os: 'windows-latest'
          - name: 'py39-cover (macos)'
            python: '3.9'
            python_arch: 'x64'
            os: 'macos-latest'
          - name: 'py39-nocov (ubuntu)'
            python: '3.9'
            python_arch: 'x64'
            os: 'ubuntu-latest'
          - name: 'py39-nocov (windows)'
            python: '3.9'
            python_arch: 'x64'
            os: 'windows-latest'
          - name: 'py39-nocov (macos)'
            python: '3.9'
            python_arch: 'x64'
            os: 'macos-latest'
          - name: 'py310-cover (ubuntu)'
            python: '3.10'
            python_arch: 'x64'
            os: 'ubuntu-latest'
          - name: 'py310-cover (windows)'
            python: '3.10'
            python_arch: 'x64'
            os: 'windows-latest'
          - name: 'py310-cover (macos)'
            python: '3.10'
            python_arch: 'x64'
            os: 'macos-latest'
          - name: 'py310-nocov (ubuntu)'
            python: '3.10'
            python_arch: 'x64'
            os: 'ubuntu-latest'
          - name: 'py310-nocov (windows)'
            python: '3.10'
            python_arch: 'x64'
            os: 'windows-latest'
          - name: 'py310-nocov (macos)'
            python: '3.10'
            python_arch: 'x64'
            os: 'macos-latest'
          - name: 'pypy311-cover (ubuntu)'
            python: '3.11'
            python_arch: 'x64'
            os: 'ubuntu-latest'
          - name: 'pypy311-cover (windows)'
            python: '3.11'
            python_arch: 'x64'
            os: 'windows-latest'
          - name: 'pypy311-cover (macos)'
            python: '3.11'
            python_arch: 'x64'
            os: 'macos-latest'
          - name: 'pypy311-nocov (ubuntu)'
            python: '3.11'
            python_arch: 'x64'
            os: 'ubuntu-latest'
          - name: 'pypy311-nocov (windows)'
            python: '3.11'
            python_arch: 'x64'
            os: 'windows-latest'
          - name: 'pypy311-nocov (macos)'
            python: '3.11'
            python_arch: 'x64'
            os: 'macos-latest'
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.python_arch }}
    - name: install dependencies
      run: |
        python -m pip install --progress-bar=off 'chromex[test]'
        pip --version
        pip list --format=freeze
    - name: test
      run: >
        pytest --trace --color=yes
